// Auto-generated by mondeto/script/export-abi.py — do not edit by hand.
// Regenerate: cd ../mondeto && uv run python3 script/export-abi.py

export const MONDETO_ADDRESS = '0x63a514b04b0eff231d26837790690e1dd4010e7d' as const
export const USDT_ADDRESS = '0x471EcE3750Da237f93B8E339c536989b8978a438' as const

export const MONDETO_ABI = [
  {"type":"constructor","inputs":[{"name":"_width","type":"uint16","internalType":"uint16"},{"name":"_height","type":"uint16","internalType":"uint16"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"HALVING_TIME","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"HEIGHT","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"LAND_MASK_LENGTH","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"TOTAL_PIXELS","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"WIDTH","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"buyPixels","inputs":[{"name":"ids","type":"uint256[]","internalType":"uint256[]"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"config","inputs":[],"outputs":[{"name":"width","type":"uint16","internalType":"uint16"},{"name":"height","type":"uint16","internalType":"uint16"},{"name":"halvingTime","type":"uint256","internalType":"uint256"},{"name":"_initialPrice","type":"uint256","internalType":"uint256"},{"name":"_minPrice","type":"uint256","internalType":"uint256"},{"name":"_deployTimestamp","type":"uint256","internalType":"uint256"},{"name":"_feeRate","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"currentEpoch","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"deployTimestamp","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"feeRate","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"getPixelBatch","inputs":[{"name":"x","type":"uint16","internalType":"uint16"},{"name":"y","type":"uint16","internalType":"uint16"},{"name":"w","type":"uint16","internalType":"uint16"},{"name":"h","type":"uint16","internalType":"uint16"}],"outputs":[{"name":"","type":"bytes","internalType":"bytes"}],"stateMutability":"view"},
  {"type":"function","name":"initialPrice","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"isLand","inputs":[{"name":"x","type":"uint16","internalType":"uint16"},{"name":"y","type":"uint16","internalType":"uint16"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"landMask","inputs":[{"name":"","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"minPrice","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"pixelId","inputs":[{"name":"x","type":"uint16","internalType":"uint16"},{"name":"y","type":"uint16","internalType":"uint16"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"pixels","inputs":[{"name":"","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"saleCount","type":"uint8","internalType":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"priceOf","inputs":[{"name":"x","type":"uint16","internalType":"uint16"},{"name":"y","type":"uint16","internalType":"uint16"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"profiles","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"color","type":"uint24","internalType":"uint24"},{"name":"label","type":"bytes","internalType":"bytes"},{"name":"url","type":"bytes","internalType":"bytes"}],"stateMutability":"view"},
  {"type":"function","name":"rectanglePrice","inputs":[{"name":"x","type":"uint16","internalType":"uint16"},{"name":"y","type":"uint16","internalType":"uint16"},{"name":"w","type":"uint16","internalType":"uint16"},{"name":"h","type":"uint16","internalType":"uint16"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"selectionPrice","inputs":[{"name":"ids","type":"uint256[]","internalType":"uint256[]"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"updateProfile","inputs":[{"name":"color","type":"uint24","internalType":"uint24"},{"name":"label","type":"string","internalType":"string"},{"name":"url","type":"string","internalType":"string"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"withdraw","inputs":[{"name":"to","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"PixelsPurchased","inputs":[{"name":"buyer","type":"address","indexed":true,"internalType":"address"},{"name":"ids","type":"uint256[]","indexed":false,"internalType":"uint256[]"},{"name":"totalCost","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"ProfileUpdated","inputs":[{"name":"user","type":"address","indexed":true,"internalType":"address"},{"name":"color","type":"uint24","indexed":false,"internalType":"uint24"},{"name":"label","type":"bytes","indexed":false,"internalType":"bytes"},{"name":"url","type":"bytes","indexed":false,"internalType":"bytes"}],"anonymous":false},
  {"type":"error","name":"InvalidCoordinates","inputs":[]},
  {"type":"error","name":"InvalidFeeRate","inputs":[]},
  {"type":"error","name":"InvalidMaskLength","inputs":[]},
  {"type":"error","name":"InvalidPixelId","inputs":[{"name":"id","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"LabelTooLong","inputs":[]},
  {"type":"error","name":"NotLand","inputs":[{"name":"id","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"OutOfBounds","inputs":[]},
  {"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address","internalType":"address"}]},
  {"type":"error","name":"UrlTooLong","inputs":[]},
] as const

export const USDT_ABI = [
  {"type":"function","name":"approve","inputs":[{"name":"spender","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"allowance","inputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"spender","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"balanceOf","inputs":[{"name":"account","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
] as const
